version: 0.0
os: linux
files:
  - source: /imagedefinitions.json
    destination: /opt/codedeploy-agent/deployment-root/deployment-instructions/
hooks:
  AfterInstall:
    - location: deploy/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/start_application.sh
      timeout: 300
      runas: root
environment_variables:
  ECR_URI: 
    value: "767397895765.dkr.ecr.us-east-1.amazonaws.com/endowdafrica_05:latest"
    type: plaintext