version: 0.0
os: linux
files:
  - source: /imagedefinitions.json
    destination: /opt/codedeploy-agent/deployment-root/deployment-instructions/
hooks:
  BeforeInstall:
    - location: deploy/create_env_vars.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/start_application.sh
      timeout: 300
      runas: root
