version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 767397895765.dkr.ecr.us-east-1.amazonaws.com
  
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t endowdafrica:latest .
      - docker tag endowdafrica:latest 767397895765.dkr.ecr.us-east-1.amazonaws.com/endowdafrica_37:latest
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 767397895765.dkr.ecr.us-east-1.amazonaws.com/endowdafrica_37:latest
      - echo Writing image definitions file...
      - printf '[{"name":"endowdAfrica","imageUri":"%s"}]' 767397895765.dkr.ecr.us-east-1.amazonaws.com/endowdafrica_37:latest > imagedefinitions.json

artifacts:
  files: 
    - imagedefinitions.json
    - appspec.yml
